language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"

notifications:
  email: false
  
env:
  - TWFY_TEST_DB_HOST=localhost
  - TWFY_TEST_DB_USER=root
  - TWFY_TEST_DB_PASS=
  - TWFY_TEST_DB_NAME=twfy_test
  
before_script:
 - mysql -e "create database IF NOT EXISTS twfy_test;" -uroot
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v