name: Push mirror to git.mysociety.org

on:
  push:
  workflow_dispatch:
    inputs:
      force_push:
        description: 'Force push branch'
        type: boolean
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Push branch to git.mysociety.org
      id: push_to_mirror
      if: ${{ github.event.inputs.force_push == 'false' || !github.event.inputs.force_push }}
      uses: mysociety/action-git-pusher@v1.3.0
      with:
        git_ssh_key: ${{ secrets.PUBLICCVS_GIT_KEY }}
        ssh_known_hosts: ${{ secrets.GIT_KNOWN_HOSTS }}
        tag: ${{ github.ref_name }} 
        remote: 'ssh://gh-public@git.mysociety.org/data/git/public/theyworkforyou.git'


    - name: Push branch to git.mysociety.org (force)
      id: push_to_mirror_force
      if: ${{ github.event.inputs.force_push == 'true' }}
      uses: mysociety/action-git-pusher@v1.3.0
      with:
        git_ssh_key: ${{ secrets.PUBLICCVS_GIT_KEY }}
        ssh_known_hosts: ${{ secrets.GIT_KNOWN_HOSTS }}
        tag: ${{ github.ref_name }} 
        remote: 'ssh://gh-public@git.mysociety.org/data/git/public/theyworkforyou.git'
        extra_git_config: --force
